spring:
  application:
    name: clover

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/clover
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

  cloud:
    aws:
      credentials:
        access-key: 여기에_액세스키
        secret-key: 여기에_시크릿키
      region:
        static: ap-northeast-2
      s3:
        endpoint: https://sgp1.digitaloceanspaces.com

jwt:
  secret: 임시시크릿
  access-token-validity-in-milliseconds: 86400000